image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install

test:
  stage: test
  script:
    - npm test
    # - npm run test:coverage
  # artifacts:
  #   paths:
  #     - coverage
  #   untracked: false
  #   expire_in: 30 days
